### ISSUE TITLE
Adding new Movie fill in details from API

### ISSUE THREAD

**Issue by dan-westall** [humanmade/retreat-2017-automated-testing#1]
When adding a new movie search an api and fill in the description and cover art from api

**Comment by paulgibbs** [comment]
Note for future: the cover art URLs look like so:

http://image.tmdb.org/t/p/w640/inVq3FRqcYIRl2la8iZikYYxFNR.jpg

where `w640` is the width of the image you want back
and the last path is either `poster_path` or `backdrop_path` (not sure difference) from a film response.
