### ISSUE TITLE
Default Movie Set

### ISSUE THREAD

**Issue by dan-westall** [humanmade/retreat-2017-automated-testing#4]
On plugin installation add a default movie roster

**Comment by paulgibbs** [comment]
Install script (look in .workshop/install.sh, which is mounted at /etc/workshop/install.sh) does:

* Installs Composer.
* Activate our plugin and theme.
* Sets permalink structure, and flushes.
* Creates nav menu and item so you can get to "movies" from the primary navigation on the theme, for convenience.
* Sets show-post-on-homepage and creates a new post for this, that adds a shortcode `add_movie_form` which will render the "add new movie" form.
* Stubbed out `add_movie_form` shortcode, doesn't do anything (yet).
* Adds all the BBFC ratings (Universal through to R18) as terms in the "rating" taxonomy.
* Adds *one* genre (Action) as a term in the "genre" taxonomy. Stores themoviedb's ID for this genre (action = 28, see content/plugins/movieplugin/*.json) as term meta for this with key "genre_id".
* Adds *one* sample movie (Deadpool). Sets appropriate values in rating/genre taxonomies. Sideloads album art and adds as featured image. themoviedb response doesn't contain BBFC ratings so yolo.

**Comment by paulgibbs** [comment]
content/plugins/movieplugin/films.json contains the top 40 films from themoviedb (I made the request twice, paged, and merged the results).

content/plugins/movieplugin/genres.json contains all *film* genres from themoviedb.
